# .streamlit/config.toml

[server]
headless = true
port = $PORT
enableCORS = false

[theme]
primaryColor = "#007bff"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"
